services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
    env_file:
      - ./.env

volumes:
  redis-data:
   